use master
go

create database Ej_N1

use Ej_N1
go

create table Lugar(
	L_CODIGO INT NOT NULL PRIMARY KEY,
	L_NOMBRE VARCHAR(10) NOT NULL, 
	L_TIPO VARCHAR(10) NOT NULL,
	L_CLIMA VARCHAR(10) NOT NULL, 
	L_TOTAL_HABITANTES INT NOT NULL,
	L_DESCRIPCION VARCHAR(10) NOT NULL,
	L_LUGARES INT NOT NULL CONSTRAINT L_FK_LUGAR FOREIGN KEY (L_LUGARES) REFERENCES Lugar(L_CODIGO)
);

CREATE TABLE Pasajero(
	P_CODIGO INT NOT NULL PRIMARY KEY,
	P_NOMBRE VARCHAR(10) NOT NULL,
	P_APELLIDO VARCHAR(10) NOT NULL,
	P_PERFIL VARCHAR(10) NOT NULL,
	P_FECHA_NACIMIENTO DATE NOT NULL,
	P_NUM_TELEFONICO VARCHAR(14) UNIQUE NOT NULL,
	P_LUGAR INT NOT NULL CONSTRAINT P_FK_LUGAR_PAIS_RESIDENCIA FOREIGN KEY (P_LUGAR) REFERENCES Lugar(L_CODIGO)
);

CREATE TABLE Viaje(
	V_CODIGO INT IDENTITY NOT NULL PRIMARY KEY,
	V_PASAJERO INT NOT NULL CONSTRAINT V_FK_PASAJERO FOREIGN KEY(V_PASAJERO) REFERENCES Pasajero(P_CODIGO),
	V_LUGAR INT NOT NULL CONSTRAINT V_FK_LUGA FOREIGN KEY (V_LUGAR) REFERENCES Lugar(L_CODIGO),
	V_FECHA DATE NOT NULL
);

select * from Lugar

Insert into Pasajero(P_CODIGO,P_NOMBRE,P_APELLIDO,P_FECHA_NACIMIENTO,P_PERFIL,P_NUM_TELEFONICO,P_LUGAR)values
(3,'Magali','Said','2001-05-01','prima','112378317',3) 

select P_NOMBRE AS Nombre, P_APELLIDO as Apellido 
from Pasajero

select L_NOMBRE, L_TOTAL_HABITANTES,L_TOTAL_HABITANTES+100000 as L_INCREMENTO_TOTAL_HABITANTES 
from Lugar;

update Lugar
set L_CLIMA='Tropical'
where L_NOMBRE='Mexico';

select L_NOMBRE,L_CLIMA
FROM Lugar 
WHERE L_CLIMA<>'Mediterraneo'; 

UPDATE Lugar
set L_CLIMA='Mediterraneo'
WHERE L_NOMBRE='USA';

select L_NOMBRE
FROM Lugar
where L_NOMBRE like '%a%';

Insert into Pasajero(P_CODIGO,P_NOMBRE,P_APELLIDO,P_FECHA_NACIMIENTO,P_PERFIL,P_NUM_TELEFONICO,P_LUGAR)values
(9,'Angela','Ruiz','2001-05-01','LowCost','17128310',3) 

select L_NOMBRE
FROM Lugar
where L_TIPO<>'Continente'

select * from Pasajero

select P_NOMBRE, P_APELLIDO  
from Pasajero,Lugar
where Pasajero.P_APELLIDO='Selem'
and Lugar.L_TIPO='Pais'
and Lugar.L_NOMBRE <>'Argentina'
and Pasajero.P_LUGAR=Lugar.L_CODIGO
order by Pasajero.P_PERFIL,Pasajero.P_NOMBRE