use master
go

create database Ej1DDL

use Ej1DDL
go

create table PUB(
COD_PUB VARCHAR(10) NOT NULL PRIMARY KEY (COD_PUB),
NOMBRE VARCHAR(10) NOT NULL,
LICENCIA_FISCAL VARCHAR(10) NOT NULL,
DOMICILIO VARCHAR(10),
FECHA_APERTURA DATE NOT NULL,
HORARIO VARCHAR(10) NOT NULL CHECK (HORARIO IN ('HOR1','HOR2','HOR3')),
COD_LOCALIDAD INT NOT NULL CONSTRAINT FK_PUB_COD_LOCALIDAD FOREIGN KEY(COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)
);

CREATE TABLE TITULAR(
DNI_TITULAR VARCHAR(10) NOT NULL PRIMARY KEY(DNI_TITULAR),
NOMBRE VARCHAR(10) NOT NULL,
DOMICILIO VARCHAR(10) ,
COD_PUB VARCHAR(10) NOT NULL CONSTRAINT FK_TITULAR_COD_PUB FOREIGN KEY(COD_PUB) REFERENCES PUB(COD_PUB)
);

CREATE TABLE EMPLEADO(
DNI_EMPLEADO VARCHAR(10) NOT NULL PRIMARY KEY (DNI_EMPLEADO),
NOMBRE VARCHAR(10) NOT NULL,
DOMICILIO VARCHAR(10)
);

CREATE TABLE EXISTENCIAS(
COD_ARTICULO VARCHAR(10) NOT NULL PRIMARY KEY(COD_ARTICULO),
NOMBRE VARCHAR(10) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO INT NOT NULL CHECK(PRECIO>0),
COD_PUB VARCHAR(10) NOT NULL CONSTRAINT FK_EXISTENCIAS_COD_PUB FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
);

CREATE TABLE LOCALIDAD(
COD_LOCALIDAD INT NOT NULL PRIMARY KEY (COD_LOCALIDAD),
NOMBRE VARCHAR(10) NOT NULL
);

CREATE TABLE PUB_EMPLEADO(
COD_PUB  VARCHAR(10) NOT NULL CONSTRAINT FK_PUB_EMPLEADO_COD_PUB FOREIGN KEY(COD_PUB) REFERENCES PUB(COD_PUB),
DNI_EMPLEADO VARCHAR(10) NOT NULL CONSTRAINT FK_PUB_EMPLEADO_DNI_EMPLEADO FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO),
FUNCION VARCHAR(10) NOT NULL CHECK(FUNCION IN('CAMARERO','SEGURIDAD','LIMPIEZA')),
CONSTRAINT PK_PUB_EMPLEADO PRIMARY KEY (COD_PUB, DNI_EMPLEADO, FUNCION)
);